language: ruby
rvm:
  - 2.2.2
script:
    - RAILS_ENV=test bundle exec rake db:migrate --trace db:migrate test
    - bundle exec rake db:test:prepare
    - bundle exec rspec spec/
env:
  - DB=postgresql
before_script:
  - psql -c 'create database chess_test' -U postgres
bundler_args: --binstubs=./bundler_stubs
